[package]
name = "slope"
version = "0.1.0"
authors = ["Ben Russell <bprussell80@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "*"
itertools = "*"
rust_decimal = "*"
